### ISSUE TITLE
Novice needing clarification on ./setup

### ISSUE THREAD

**Issue by nigelhaslam** [aktos-io/dcs-tools#11]
#Direct connection settings:
------------------------------------------------------------------
**NODE_IP**    Is the IP address of the Raspberry Pi or the machine connecting to it?
**MOUNT_DIR=$(mktemp -d)** what is this?

**Comment by ceremcem** [comment]
`NODE` is the target "Raspberry Pi" (or more generally, the target Linux machine). Thus, `NODE_IP` is the IP address of the machine you want to connect to. 

`MOUNT_DIR` variable exists for optional mount location for `sshfs`. The reason behind this option is that if you mount your target to a regular directory somewhere in your project folder (eg. `/home/you/myprojects/remote-x/NODE`) and leave it mounted, chances are you will make your (hourly) PC backups before unmounting it. Which will lead starting to backup whole target machine erroneously. That's why this variable lets you mount your target machine (the `NODE`) to a randomly named temporary directory (in `/tmp`) and create a symlink to it from your project directory. 

Any naming suggestions are welcome.

**Comment by nigelhaslam** [comment]
Thanks Cerem,

I have to go out on a shoot now but I'll try and follow your directions in
the morning.

Have a great day!

N

*Nigel Haslam* *| Director *

*Motion Circus Pty Ltd. Byron Bay*
*t**: + 61 2 8007 7338 **|**m**: * *+ 61  403 020 126*
*w: www.motioncircus.com <http://www.motioncircus.com/>*
link to website <http://motioncircus.com>

**Comment by nigelhaslam** [comment]
Hi,

Sorry, I missed this email this morning when I first replied.

So when you say hourly PC backups, you are talking about the back up
routine of your local, laptop machine, which, if it had the remote (NODE /
target / RaspberryPi) mounted, as a local drive, your PC backup would think
that it had to back up the remote NODE as well, because it would simply see
it as another folder?

I'm grasping a little here but it kind of make sense.  I'm not familiar
with symlinks though, they sound like 'pointers' to data, rather than the
data itself.  Which makes me think that if the randomly named temporary
directory was removed. then the symlink pointer would be pointing at
nothing.  Are your hourly backup systems configured to ignore the tmp
folder?

Cheers

Nigel

*Nigel Haslam* *| Director *

*Motion Circus Pty Ltd. Byron Bay*
*t**: + 61 2 8007 7338 **|**m**: * *+ 61  403 020 126*
*w: www.motioncircus.com <http://www.motioncircus.com/>*
link to website <http://motioncircus.com>

**Comment by nigelhaslam** [comment]
I just logged a new issue about symlinks.. I'm afraid they may be a
showstopper for PC jockeys like me:(

Tell me it ain't so

N

*Nigel Haslam* *| Director *

*Motion Circus Pty Ltd. Byron Bay*
*t**: + 61 2 8007 7338 **|**m**: * *+ 61  403 020 126*
*w: www.motioncircus.com <http://www.motioncircus.com/>*
link to website <http://motioncircus.com>

**Comment by ceremcem** [comment]
Closed by https://github.com/aktos-io/dcs-tools/blob/master/doc/configuration.md
